title: Hey, That's Hell You're Walking Into
author: SirisKiO
email: regretkyotosin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey, that's hell you're walking into.

# social links
github_username:  SirisKiO

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
